version: '3'

volumes:
    db:
        driver: ${PGSQL_DRIVER}
    buildbot:
        driver: ${VOLUMES_DRIVER}
    worker:
        driver: ${VOLUMES_DRIVER}

services:

  db:
    image: "postgres:9.4"
    expose:
        - 5432
    env_file: .env

  buildbot:
    build: ./master
    links:
        - db
    expose:
        - 8080
        - 9989
    ports:
      - 8080:8080
    depends_on:
        - db
    env_file: .env

  worker:
    build: ./worker
    links:
        - buildbot
    depends_on:
        - buildbot
    env_file: .env

  worker_win:
    build: ./worker_wine
    links:
        - buildbot
    depends_on:
        - buildbot
    env_file: .env
