version: '3'

volumes:
    db:
        driver: ${PGSQL_DRIVER}
    buildbot:
        driver: ${VOLUMES_DRIVER}
    worker:
        driver: ${VOLUMES_DRIVER}

services:

  db:
    image: "postgres:9.4"
    expose:
        - 5432
    env_file: .env

  buildbot:
    build: ./master
    links:
        - db
    expose:
        - 8080
        - 9989
    ports:
      - 8080:8080
    depends_on:
        - db
    env_file: .env

  worker:
    build: ./worker
    environment:
      BUILDMASTER: ${UX_BUILDMASTER}
      BUILDMASTER_PORT: ${UX_BUILDMASTER_PORT}
      WORKERNAME: ${UX_WORKERNAME}
      WORKERPASS: ${UX_WORKERPASS}
      WORKER_ENVIRONMENT_BLACKLIST: ${BASE_WORKER_ENVIRONMENT_BLACKLIST}
    links:
        - buildbot
    depends_on:
        - buildbot


  worker_win:
    build: ./worker_wine
    environment:
      BUILDMASTER: ${WN_BUILDMASTER}
      BUILDMASTER_PORT: ${WN_BUILDMASTER_PORT}
      WORKERNAME: ${WN_WORKERNAME}
      WORKERPASS: ${WN_WORKERPASS}
      WORKER_ENVIRONMENT_BLACKLIST: ${BASE_WORKER_ENVIRONMENT_BLACKLIST}
    links:
        - buildbot
    depends_on:
        - buildbot
